### PR TITLE
Initial design upgrade

### PR DESCRIPTION
**Pull request by felipesere**
Basically make it look... less boring.

### CODE REVIEW

**Comment by marosluuce** [comment]
Most of this looks fine, but I'm not a good judge. We should definitely sit down and figure out if hiding skeleton inside of our own classes is better than using it explicitly.

**Comment by Maikon** [comment]
@marosluuce :+1: I remember when Christoph wrote this: https://blog.8thlight.com/christoph-gockel/2014/10/07/abotw-isolating-css.html until then I never thought of doing the same for CSS

**Comment by christophgockel** [comment]
I'm pulling it down tonight to check it out.
Are we sure we want to pull in Skeleton as a dependency? I dislike CSS "frameworks" in general.

How about we do the minimal amount of CSS work ourselves?

**Comment by marosluuce** [comment]
If you know how to do the styling then great. I'm fine using a framework if we hide it and are sensible. If we don't need it then we can get rid of it.

**Comment by Maikon** [comment]
I think there's value in attempting to improve our design skills and in effect get better at HTML/CSS so dropping the framework can help towards to that but yeah...

**Comment by felipesere** [comment]
Drop Skeleton but keep SCSS/brunch right? I may give it a ago tonight. Though I'd try to keep the look and feel.

**Comment by christophgockel** [comment]
Replaced `<div>`s with better suited HTML5 elements.

Pulled Skeleton out completely now. Once we know more about how we want it to look and feel let's see how we organise our own classes in a way that doesn't leak the "grid" knowledge into the markup.

**Comment by christophgockel** [comment]
Rebased master into this branch and updated the styling for Papers.

**Pull request merged**
